task_name: boolq
method: prompt_tuning
plm: t5-base

boolq:
  prompt_tuning:
    gpt2:
      tokenizer_name: gpt2
      learning_rate: 0.01
    t5-base:
      learning_rate: 0.001
      tokenizer_name: t5-base
    roberta:
      learning_rate: 0.001
